name: CloudStream Derleyici

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.py"
      - "**/*.m3u"
      - "**/*.m3u8"

jobs:
  CloudStreamDerleyici:
    runs-on: ubuntu-latest

    steps:
      - name: "'src' Depo Kontrolü"
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: "'build' Depo Kontrolü"
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"

      - name: Eski Derlemeleri Temizle
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: JDK 17 Ayarla
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Android SDK Ayarla
        uses: android-actions/setup-android@v3

      - name: Gradle Önbelleğini Temizle
        run: rm -rf ~/.gradle/caches/

      - name: CloudStream Eklentilerini Derle (.cs3 üretimi)
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew :app:assembleRelease || true
          ./gradlew make makePluginsJson
          find . -type f -name "*.cs3" -exec cp {} $GITHUB_WORKSPACE/builds \;
          if [ -f build/plugins.json ]; then
            cp build/plugins.json $GITHUB_WORKSPACE/builds
          fi

      - name: Derlemeleri Yükle
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "${{ github.sha }} sürümü derlendi (.cs3 oluşturuldu)" || echo "Değişiklik yok"
          git push origin builds --force
