name: CloudStream Kaynak Kontrolü

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.png"
      - "**/*.jpg"
  workflow_dispatch:

jobs:
  kontrol:
    runs-on: ubuntu-latest
    steps:
      - name: Derleyici workflow’unu tetikle
        uses: peter-evans/workflow-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          workflow: "Derleyici.yml"
          ref: main
